version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo_db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"

  products:
    build: 
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    environment:
      DB_URL: "mongodb://mongo_db/shopping_ms_products"
    depends_on:
      - "mongo_db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/products/node_modules  

  user:
    build: 
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8001:8001"
    restart: always
    environment:
      DB_URL: "mongodb://mongo_db/shopping_ms_user"
    depends_on:
      - "mongo_db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/user/node_modules

  shopping:
    build: 
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    environment:
      DB_URL: "mongodb://mongo_db/shopping_ms_shopping"
    depends_on:
      - "mongo_db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/shopping/node_modules
 
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - user
    ports:
      - 81:80


